FROM node:20-alpine

WORKDIR /app

# Copiamos dependencias
COPY package*.json ./
RUN npm install

# Copiamos el resto del código
COPY . .

# En desarrollo usamos nodemon directamente
CMD ["npm", "run dev"]